# Generated by Django 5.1.2 on 2024-10-31 14:41

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to=users.models.get_profile_image_upload_path),
        ),
    ]
